### ISSUE TITLE
How to have different $jc_effect_EFFECT_desc for different gem tiers? 

### ISSUE THREAD

**Issue by FroggerHH** [blaxxun-boop/Jewelcrafting#67]

**Comment by blaxxun-boop** [comment]
V1.5.0 allows you to specify different texts for different tiers now, in addition to the general description.

```yml
jc_effect_whirlwind: "Whirlwind"
jc_effect_whirlwind_desc: "Increases your movement speed."
jc_effect_whirlwind_desc_detail: "Movement speed increased by $1%."
jc_effect_whirlwind_desc_1: "Makes you a lot faster."
jc_effect_whirlwind_desc_1_detail: "Movement speed increased a lot by $1%."
jc_effect_whirlwind_desc_2: "Makes you super fast."
jc_effect_whirlwind_desc_2_detail: "Speed up by $1%."
jc_effect_whirlwind_desc_3: "Makes you lightning fast."
jc_effect_whirlwind_desc_3_detail: "Speed up by insane $1%."
```
